import { randomUUID } from "node:crypto";
import { mkdir, readdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.resolve(__dirname, "..", "data");
const designsDir = path.join(dataDir, "designs");

// IDs are also filenames, so only accept the canonical UUID shape generated by
// randomUUID(). This intentionally allows any UUID version for compatibility
// with designs created by older releases or imported from other tools.
export const DESIGN_ID_PATTERN = /^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i;

async function ensureStore() {
  await mkdir(designsDir, { recursive: true });
}

function normalizeDesign(design) {
  const now = new Date().toISOString();
  const id = design.id ?? randomUUID();

  if (typeof id !== "string" || !DESIGN_ID_PATTERN.test(id)) {
    throw new TypeError("Design id must use the canonical UUID format.");
  }

  return {
    ...design,
    id,
    updatedAt: now
  };
}

function resolveStoreFile(fileName) {
  const root = path.resolve(designsDir);
  const target = path.resolve(root, fileName);
  const relative = path.relative(root, target);

  if (!relative || relative === ".." || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) {
    throw new Error("Resolved design path is outside the design store.");
  }

  return target;
}

export async function saveDesign(design) {
  const normalized = normalizeDesign(design);
  const target = resolveStoreFile(`${normalized.id}.json`);
  const temporaryTarget = resolveStoreFile(`.${normalized.id}.${process.pid}.${randomUUID()}.tmp`);

  await ensureStore();
  try {
    await writeFile(temporaryTarget, JSON.stringify(normalized, null, 2), { encoding: "utf8", flag: "wx" });
    await rename(temporaryTarget, target);
  } finally {
    await rm(temporaryTarget, { force: true });
  }

  return normalized;
}

export async function listDesigns() {
  await ensureStore();
  const files = await readdir(designsDir);
  const designs = [];

  for (const file of files.filter((entry) => DESIGN_ID_PATTERN.test(path.basename(entry, ".json")) && entry.endsWith(".json"))) {
    const content = await readFile(resolveStoreFile(file), "utf8");
    designs.push(JSON.parse(content));
  }

  return designs.sort((left, right) => String(right.updatedAt).localeCompare(String(left.updatedAt)));
}
